version: "3"
services:
  app:
    container_name: express-mongo
    restart: always
    command: npm run dev
    build: ./
    ports:
      - "7000:7000"
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
